### PR TITLE
Revert es6 to es2015

### PR DESCRIPTION
**Pull request by haletothewood**
This is because node.js does not support es6 out the box.

We can use babel if we wish but this PR just reverts a previous breaking change. Any additional changes should be in a separate PR.

### CODE REVIEW

**Comment by TomSpencerLondon** [comment]
This looks great David! Can we not use babel?...

**Review by TomSpencerLondon — COMMENTED** [review]
This looks like a refactoring for the mongodb connection... Looks good...

**Comment by haletothewood** [comment]
> This looks like a refactoring for the mongodb connection... Looks good...

Hey Tom, this PR just reverts the changes I made to the es2015 syntax in a previous PR.

**Comment by TomSpencerLondon** [comment]
Thank you David! I will have a look at this...

**Review by edlowther — APPROVED** [review]

**Pull request merged**
